manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: arabshapt
      url-base: https://github.com/arabshapt
  projects:
    - name: zmk
      remote: arabshapt
      revision: main
      import: app/west.yml
  self:
    path: config
